# Assignment 1

### 1) Write a module AddNum which have two functions Add(a,b) and Sub(a,b) which perform the addition and subtraction of two numbers respectively. Import AddNum module into your Jupyter notebook or in other IDE and call these functions.

In [1]:
import sys

In [2]:
sys.path += ["C:\\Users\\Dhruvil\\Desktop\\Dhruvil PDEU\\PDEU All Sem\\PDEU 6th Sem\\Artificial Intelligence\\Lab\\Assignments\\Assignment 1"]

In [3]:
import AddNum

sumOfNumbers = AddNum.Add(5,8)
subOfNumbers = AddNum.Sub(9,5)

print("Addition of 5 and 8 is :", sumOfNumbers)
print("Subtraction of 9 and 5 is :", subOfNumbers)

Addition of 5 and 8 is : 13
Subtraction of 9 and 5 is : 4


### 2)	WAP to count the number of files in a single directory.

In [4]:
import os

In [5]:
totalFiles = os.listdir("C:\\Users\\Dhruvil\\Desktop\\Dhruvil\\Web Development\\Web Development Projects")
print("Total no of files/folders in this Directory are :", len(totalFiles))

Total no of files/folders in this Directory are : 34


### 3)	Create an 8x8 matrix and fill it with a checkerboard pattern.

In [6]:
import numpy as np

In [7]:
arr = np.zeros([8, 8], dtype = int)

In [8]:
arr[1::2, ::2] = 1
print(arr)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [9]:
arr[::2, 1::2] = 1
print("Checkboard pattern is created below using Slicing Operation\n")
print(arr)

Checkboard pattern is created below using Slicing Operation

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 4)	WAP to find common values between two arrays

In [10]:
def findCommonValues(arr1, arr2):
    if arr1 == [] or arr2 == []:
        return []
    elif arr1[0] < arr2[0]:
        return findCommonValues(arr1[1:], arr2)
    elif arr1[0] > arr2[0]:
        return findCommonValues(arr1, arr2[1:])
    else:
        return [arr1[0]] + findCommonValues(arr1[1:], arr2[1:])

arr1 = [4, 6, 2, 7, 9, 1, 16, 10, 30]
arr2 = [3, 5, 4, 6, 12, 8, 15, 2, 16]

arr1.sort()
arr2.sort()
    
print("Common Elements are :", findCommonValues(arr1, arr2))

Common Elements are : [2, 4, 6, 16]


### 5)	WAP to add a border (filled with 0's) around an existing array.  

In [11]:
arr = np.zeros([5,5])

In [12]:
arr[1:-1, 1:-1] = 1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
